version: "3.9"
services:
  ai_python:
    build:
      context: .
      dockerfile: Dockerfile
    image: "ai_python_image"
    container_name: "ai_pyton_container"
    ports:
      - 7070:8080
    volumes:
      - /:/homme/app
    tty: true